spring.datasource.url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

camunda.bpm.admin-user:
  id: demo
  password: demo

spring.h2.console:
  enabled: true
  path: /h2-console

migration:
  sourceDefinition:
    key: "motor-finance-application"
    version: "1.0.0"
  targetDefinition:
    key: "motor-finance-application"
    version: "2.0.0"
  updateEventTriggers: false
  skipIoMappings: false
  skipCustomListeners: false